In [1]:
import numpy as np

In [2]:
class NeuralNetwork():
    def __init__(self):
        np.random.seed(1)
    
        # We model a single neuron, with 3 input connections and 1 output connection.
        # We assign random weights to a 3 x 1 matrix, with values in the range -1 to 1
        # and mean 0.
        self.synaptic_weights = 2 * np.random.random((3, 1)) - 1
    
    # The Sigmoid function, which describes an S shaped curve.
    # We pass the weighted sum of the inputs through this function to
    # normalise them between 0 and 1.
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    # The derivative of the Sigmoid function.
    # This is the gradient of the Sigmoid curve.
    # It indicates how confident we are about the existing weight.
    def sigmoid_derivative(self, x):
        return x * (1 - x)
    
    # We train the neural network through a process of trial and error.
    # Adjusting the synaptic weights each time.
    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in range(number_of_training_iterations):
            # Pass the training set through our neural network (a single neuron).
            output = self.predict(training_set_inputs)
            
            # print("\nOutput of the Above Function After Sigmoid Applied: \n",output)
            # Calculate the error (The difference between the desired output and the predicted output).
            error = training_set_outputs - output
            
            # print("\nTraining Set Output Matrix: \n", training_set_outputs)
            # print("\nError: Training Set Output Matrix 4x1 - Above Matrix 4x1 \n", error)
            # Multiply the error by the input and again by the gradient of the Sigmoid curve.
            # This means less confident weights are adjusted more.
            # This means inputs, which are zero, do not cause changes to the weights.
            adjustment = np.dot(training_set_inputs.T, error * self.sigmoid_derivative(output))
            
            # print("\nAdjustment Matrix: \n", adjustment)
            # Adjust the weights.
            self.synaptic_weights += adjustment
            
    # The neural network predict.
    def predict(self, inputs):
        dot_product = np.dot(inputs, self.synaptic_weights)
        # print("\nDot Product of Input Matrix and Weight Matrix: \n",dot_product)
        # Pass inputs through our neural network (our single neuron).
        return self.sigmoid(dot_product)

In [3]:
if __name__ == "__main__":
    neural_network = NeuralNetwork()
    
    print ("\n\nRandom starting synaptic weights: ")
    print (neural_network.synaptic_weights)
    
    # trinning sets # 4 x 3 matrix
    training_set_inputs = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
    
    # actual output # 4 x 1 vector
    training_set_outputs = np.array([[0, 1, 1, 0]]).T
    
    # Train the neural network using a training set.
    # Do it 10,000 times and make small adjustments each time.
    neural_network.train(training_set_inputs, training_set_outputs, 10000)
    print ("\nNew synaptic weights after training: ")
    print (neural_network.synaptic_weights)
    
    # Test the neural network with a new situation.
    print ("\nConsidering new situation [1, 0, 0] -> ?: ")
    print (neural_network.predict(np.array([1, 0, 0])))



Random starting synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]

New synaptic weights after training: 
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]

Considering new situation [1, 0, 0] -> ?: 
[0.99993704]


In [4]:
# 4 x 3 matrix
np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [5]:
# 4 x 1 vector
np.array([[0, 1, 1, 0]]).T

array([[0],
       [1],
       [1],
       [0]])

In [6]:
nn = NeuralNetwork()

In [7]:
nn.sigmoid(3), nn.sigmoid(-3)

(0.9525741268224334, 0.04742587317756678)

In [8]:
nn.sigmoid_derivative(-3), nn.sigmoid_derivative(3)

(-12, -6)

In [9]:
nn.predict(3)

array([[0.37804183],
       [0.78950545],
       [0.04745689]])